//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logica.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Urls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Urls() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Logica.Recursos.Urls", typeof(Urls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a album/.
        /// </summary>
        internal static string URLAlbum {
            get {
                return ResourceManager.GetString("URLAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://localhost:7008/.
        /// </summary>
        internal static string URLAPIGateway {
            get {
                return ResourceManager.GetString("URLAPIGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a artista/.
        /// </summary>
        internal static string URLArtista {
            get {
                return ResourceManager.GetString("URLArtista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a autenticar.
        /// </summary>
        internal static string URLAutenticar {
            get {
                return ResourceManager.GetString("URLAutenticar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a album/porid.
        /// </summary>
        internal static string URLBuscarAlbumPorId {
            get {
                return ResourceManager.GetString("URLBuscarAlbumPorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a album/pornombre.
        /// </summary>
        internal static string URLBuscarAlbumPorNombre {
            get {
                return ResourceManager.GetString("URLBuscarAlbumPorNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a album/pornombreartista.
        /// </summary>
        internal static string URLBuscarAlbumPorNombreArtista {
            get {
                return ResourceManager.GetString("URLBuscarAlbumPorNombreArtista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a album.
        /// </summary>
        internal static string URLBuscarAlbums {
            get {
                return ResourceManager.GetString("URLBuscarAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a album/poridartista.
        /// </summary>
        internal static string URLBuscarAlbumsPorIdArtista {
            get {
                return ResourceManager.GetString("URLBuscarAlbumsPorIdArtista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a artista/porid.
        /// </summary>
        internal static string URLBuscarArtistaPorId {
            get {
                return ResourceManager.GetString("URLBuscarArtistaPorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a artista/pornombre.
        /// </summary>
        internal static string URLBuscarArtistaPorNombre {
            get {
                return ResourceManager.GetString("URLBuscarArtistaPorNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a artista.
        /// </summary>
        internal static string URLBuscarArtistas {
            get {
                return ResourceManager.GetString("URLBuscarArtistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cancion.
        /// </summary>
        internal static string URLBuscarCanciones {
            get {
                return ResourceManager.GetString("URLBuscarCanciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cancion/poridalbum.
        /// </summary>
        internal static string URLBuscarCancionesPorIdAlbum {
            get {
                return ResourceManager.GetString("URLBuscarCancionesPorIdAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cancion/poridartista.
        /// </summary>
        internal static string URLBuscarCancionesPorIdArtista {
            get {
                return ResourceManager.GetString("URLBuscarCancionesPorIdArtista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cancion/porartista.
        /// </summary>
        internal static string URLBuscarCancionPorArtista {
            get {
                return ResourceManager.GetString("URLBuscarCancionPorArtista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cancion/porid.
        /// </summary>
        internal static string URLBuscarCancionPorId {
            get {
                return ResourceManager.GetString("URLBuscarCancionPorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cancion/pornombre.
        /// </summary>
        internal static string URLBuscarCancionPorNombre {
            get {
                return ResourceManager.GetString("URLBuscarCancionPorNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a porcanciongustada.
        /// </summary>
        internal static string URLBuscarMetadatosGustadosPorIdConsumidor {
            get {
                return ResourceManager.GetString("URLBuscarMetadatosGustadosPorIdConsumidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a poridcancion.
        /// </summary>
        internal static string URLBuscarMetadatosPorIdCancion {
            get {
                return ResourceManager.GetString("URLBuscarMetadatosPorIdCancion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a poridconsumidor.
        /// </summary>
        internal static string URLBuscarMetadatosPorIdConsumidor {
            get {
                return ResourceManager.GetString("URLBuscarMetadatosPorIdConsumidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a buscar/.
        /// </summary>
        internal static string URLBusqueda {
            get {
                return ResourceManager.GetString("URLBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a album/poridcancion.
        /// </summary>
        internal static string URLBusquedaAlbumPorIdCancion {
            get {
                return ResourceManager.GetString("URLBusquedaAlbumPorIdCancion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a artista/porid.
        /// </summary>
        internal static string URLBusquedaArtistaPorId {
            get {
                return ResourceManager.GetString("URLBusquedaArtistaPorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a artista/poridcancion.
        /// </summary>
        internal static string URLBusquedaArtistaPorIdCancion {
            get {
                return ResourceManager.GetString("URLBusquedaArtistaPorIdCancion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a artista/pornombre.
        /// </summary>
        internal static string URLBusquedaArtistaPorNombre {
            get {
                return ResourceManager.GetString("URLBusquedaArtistaPorNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a artista.
        /// </summary>
        internal static string URLBusquedasArtistas {
            get {
                return ResourceManager.GetString("URLBusquedasArtistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cancion/.
        /// </summary>
        internal static string URLCancion {
            get {
                return ResourceManager.GetString("URLCancion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cargarcancion.
        /// </summary>
        internal static string URLCargaDeCanciones {
            get {
                return ResourceManager.GetString("URLCargaDeCanciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a descargarcancion.
        /// </summary>
        internal static string URLDescargaDeCanciones {
            get {
                return ResourceManager.GetString("URLDescargaDeCanciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a historialdereproduccion/.
        /// </summary>
        internal static string URLHistorialDeReproduccion {
            get {
                return ResourceManager.GetString("URLHistorialDeReproduccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a poridusuario.
        /// </summary>
        internal static string URLHistorialesDeReproduccionPorIdUsuario {
            get {
                return ResourceManager.GetString("URLHistorialesDeReproduccionPorIdUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a poridcancionyidusuario.
        /// </summary>
        internal static string URLMetadatoPorIdCancionYIdUsuario {
            get {
                return ResourceManager.GetString("URLMetadatoPorIdCancionYIdUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a metadatos/.
        /// </summary>
        internal static string URLMetadatos {
            get {
                return ResourceManager.GetString("URLMetadatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a poridcancion.
        /// </summary>
        internal static string URLObtenerMetadatoPorIdCancion {
            get {
                return ResourceManager.GetString("URLObtenerMetadatoPorIdCancion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usuario/.
        /// </summary>
        internal static string URLUsuario {
            get {
                return ResourceManager.GetString("URLUsuario", resourceCulture);
            }
        }
    }
}
