//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logica.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Urls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Urls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Logica.Recursos.Urls", typeof(Urls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to album/.
        /// </summary>
        internal static string URLAlbum {
            get {
                return ResourceManager.GetString("URLAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:7008/.
        /// </summary>
        internal static string URLAPIGateway {
            get {
                return ResourceManager.GetString("URLAPIGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artista/.
        /// </summary>
        internal static string URLArtista {
            get {
                return ResourceManager.GetString("URLArtista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autenticar.
        /// </summary>
        internal static string URLAutenticar {
            get {
                return ResourceManager.GetString("URLAutenticar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to album/porid.
        /// </summary>
        internal static string URLBuscarAlbumPorId {
            get {
                return ResourceManager.GetString("URLBuscarAlbumPorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to album/pornombre.
        /// </summary>
        internal static string URLBuscarAlbumPorNombre {
            get {
                return ResourceManager.GetString("URLBuscarAlbumPorNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to album/pornombreartista.
        /// </summary>
        internal static string URLBuscarAlbumPorNombreArtista {
            get {
                return ResourceManager.GetString("URLBuscarAlbumPorNombreArtista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to album.
        /// </summary>
        internal static string URLBuscarAlbums {
            get {
                return ResourceManager.GetString("URLBuscarAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to album/poridartista.
        /// </summary>
        internal static string URLBuscarAlbumsPorIdArtista {
            get {
                return ResourceManager.GetString("URLBuscarAlbumsPorIdArtista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artista/porid.
        /// </summary>
        internal static string URLBuscarArtistaPorId {
            get {
                return ResourceManager.GetString("URLBuscarArtistaPorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artista/pornombre.
        /// </summary>
        internal static string URLBuscarArtistaPorNombre {
            get {
                return ResourceManager.GetString("URLBuscarArtistaPorNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artista.
        /// </summary>
        internal static string URLBuscarArtistas {
            get {
                return ResourceManager.GetString("URLBuscarArtistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancion.
        /// </summary>
        internal static string URLBuscarCanciones {
            get {
                return ResourceManager.GetString("URLBuscarCanciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancion/poridalbum.
        /// </summary>
        internal static string URLBuscarCancionesPorIdAlbum {
            get {
                return ResourceManager.GetString("URLBuscarCancionesPorIdAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancion/porartista.
        /// </summary>
        internal static string URLBuscarCancionPorArtista {
            get {
                return ResourceManager.GetString("URLBuscarCancionPorArtista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancion/porid.
        /// </summary>
        internal static string URLBuscarCancionPorId {
            get {
                return ResourceManager.GetString("URLBuscarCancionPorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancion/pornombre.
        /// </summary>
        internal static string URLBuscarCancionPorNombre {
            get {
                return ResourceManager.GetString("URLBuscarCancionPorNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to porcanciongustada.
        /// </summary>
        internal static string URLBuscarMetadatosGustadosPorIdConsumidor {
            get {
                return ResourceManager.GetString("URLBuscarMetadatosGustadosPorIdConsumidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to poridcancion.
        /// </summary>
        internal static string URLBuscarMetadatosPorIdCancion {
            get {
                return ResourceManager.GetString("URLBuscarMetadatosPorIdCancion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to poridconsumidor.
        /// </summary>
        internal static string URLBuscarMetadatosPorIdConsumidor {
            get {
                return ResourceManager.GetString("URLBuscarMetadatosPorIdConsumidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buscar/.
        /// </summary>
        internal static string URLBusqueda {
            get {
                return ResourceManager.GetString("URLBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to album/poridcancion.
        /// </summary>
        internal static string URLBusquedaAlbumPorIdCancion {
            get {
                return ResourceManager.GetString("URLBusquedaAlbumPorIdCancion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artista/porid.
        /// </summary>
        internal static string URLBusquedaArtistaPorId {
            get {
                return ResourceManager.GetString("URLBusquedaArtistaPorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artista/poridcancion.
        /// </summary>
        internal static string URLBusquedaArtistaPorIdCancion {
            get {
                return ResourceManager.GetString("URLBusquedaArtistaPorIdCancion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artista/pornombre.
        /// </summary>
        internal static string URLBusquedaArtistaPorNombre {
            get {
                return ResourceManager.GetString("URLBusquedaArtistaPorNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artista.
        /// </summary>
        internal static string URLBusquedasArtistas {
            get {
                return ResourceManager.GetString("URLBusquedasArtistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancion/.
        /// </summary>
        internal static string URLCancion {
            get {
                return ResourceManager.GetString("URLCancion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cargarcancion.
        /// </summary>
        internal static string URLCargaDeCanciones {
            get {
                return ResourceManager.GetString("URLCargaDeCanciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descargarcancion.
        /// </summary>
        internal static string URLDescargaDeCanciones {
            get {
                return ResourceManager.GetString("URLDescargaDeCanciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to historialdereproduccion/.
        /// </summary>
        internal static string URLHistorialDeReproduccion {
            get {
                return ResourceManager.GetString("URLHistorialDeReproduccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to poridusuario.
        /// </summary>
        internal static string URLHistorialesDeReproduccionPorIdUsuario {
            get {
                return ResourceManager.GetString("URLHistorialesDeReproduccionPorIdUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to poridcancionyidusuario.
        /// </summary>
        internal static string URLMetadatoPorIdCancionYIdUsuario {
            get {
                return ResourceManager.GetString("URLMetadatoPorIdCancionYIdUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to metadatos/.
        /// </summary>
        internal static string URLMetadatos {
            get {
                return ResourceManager.GetString("URLMetadatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to poridcancion.
        /// </summary>
        internal static string URLObtenerMetadatoPorIdCancion {
            get {
                return ResourceManager.GetString("URLObtenerMetadatoPorIdCancion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usuario/.
        /// </summary>
        internal static string URLUsuario {
            get {
                return ResourceManager.GetString("URLUsuario", resourceCulture);
            }
        }
    }
}
